name: Auto Update V2Ray Configs

on:
  schedule:
    - cron: '0 */6 * * *' # ၆ နာရီတစ်ကြိမ် အလိုအလျောက် Update လုပ်ခိုင်းခြင်း
  workflow_dispatch: # ခလုတ်နှိပ်ပြီး ကိုယ်တိုင်ချက်ချင်း Run ချင်လျှင် သုံးရန်

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Script
        run: python update_configs.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add sub.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto updated configs"
          git push
